##datasource product
spring:
  datasource:
    username: demo
    password: demo
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
    test-on-borrow: true
    validation-query: SELECT 1

server:
  port: 8888
  context-path: /
  connection-timeout: 5000
  tomcat:
    max-threads: 300
    uri-encoding: UTF-8
    basedir: /data/servertmp

test:
  msg: this is dev