spring:
    profiles:
      active: dev

    freemarker:
        allow-request-override: false
        allow-session-override: false
        cache: true
        check-template-location: true
        content-type: text/html
        expose-request-attributes: true
        expose-session-attributes: true
        expose-spring-macro-helpers: true
        suffix: .ftl
        template-encoding: UTF-8
        template-loader-path: classpath:/templates/ftl/,classpath:/templates
        settings:
            locale: zh_CN
            date_format: yyyy-MM-dd
            time_format: HH:mm:ss
            datetime_format: yyyy-MM-dd HH:mm:ss

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  
server:
  port: 8888
  context-path: /
  tomcat:
    max-threads: 300
    uri-encoding: UTF-8
    basedir: /data/servertmp
    
test:
  msg: this is origin